### ISSUE TITLE
Actividad individual a realizar por todos los integrantes: Carga de CV

### ISSUE THREAD

**Issue by angelsmart86** [MartinDeMarc/Proyecto-integrador-ISPC#13]

**Comment by nardiyenhy02** [comment]
Buenas noches equipo: 
Adjunto aquí
[CV Nardi 2022.pdf](https://github.com/MartinDeMarc/Proyecto-integrador-ISPC/files/9023899/CV.Nardi.2022.pdf)
 mi CV en el siguiente documento. 
Saludos !!!
