### ISSUE TITLE
Etica en la Informática

### ISSUE THREAD

**Issue by angelsmart86** [MartinDeMarc/Proyecto-integrador-ISPC#4]
Ética Informática
La EI (ética informática) es la disciplina que identifica y analiza el impacto de la tecnología informática en los valores sociales. Esta busca generar una guía dentro del ámbito informático para mantener los más altos estándares de integridad, seguridad, comportamiento y conducta responsable.

**Comment by MelGaray04** [comment]
**Ética Informática**
La EI (ética informática) es la disciplina que identifica y analiza el impacto de la tecnología informática en los valores sociales. Esta busca generar una guía dentro del ámbito informático para mantener los mas altos estándares de integridad, seguridad, comportamiento  y conducta responsable.

**Comment by MelGaray04** [comment]
Ética Informática
La EI (ética informática) es la disciplina que identifica y analiza el impacto de la tecnología informática en los valores sociales. Esta busca generar una guía dentro del ámbito informático para mantener los más altos estándares de integridad, seguridad, comportamiento y conducta `responsable.
